# Model configurations
models:
  targets: ["openai/gpt-4o-mini", "anthropic/claude-3-5-sonnet-latest"]

# Directories
directories:
  prompts: "prompts"

# Number of workers
workers: 3

# Prompt inclusion/exclusion settings
prompts:
  system:
    target_include: ["sys_freysa_act_1.yaml", "sys_freysa_act_2.json"] # List of system prompt files to include
    # target_exclude: [] # List of system prompt files to exclude
  user:
    target_include: [
        "user_freysa_act_1_winner.yaml",
        "user_freysa_act_2_winner.json",
      ] # List of user prompt files to include
    # target_exclude: ["1.yaml"] # List of user prompt files to exclude
prompt_settings:
  temperature:
  top_p:
