# Model configurations
models:
  # default: "anthropic/claude-3-5-sonnet-20241022"
  targets: ["openai/gpt-4o-mini", "anthropic/claude-3-5-sonnet-20241022"]
  # default: "groq/llama-3.2-90b-vision-preview"
  judge: "groq/llama-3.1-70b-versatile"

# Directories
directories:
  prompts: "prompts"

# Number of workers
workers: 3

# Prompt inclusion/exclusion settings
prompts:
  system:
    target_include: ["sys_freysa.yaml"] # List of system prompt files to include
    # target_exclude: [] # List of system prompt files to exclude
    example_include: ["sys_example.yaml"]
  user:
    target_include: ["user_freysa.yaml", "user_act2_winner.json"] # List of user prompt files to include
    # target_exclude: ["1.yaml"] # List of user prompt files to exclude
    example_include: ["user_example.json"]
prompt_settings:
  temperature:
  top_p:
